"""
This file serves as an index for our custom-defined spending categories, where:

- `name` is the `atcg_ln_dscr` value from the eCheckbook dataset
- `cat` is our custom category

Note that we decided to referece the `atcg_ln_dscr` instead of the commodity codes (`comm_cd`) because not all
rows have a commodity code.
"""
ACTG_LN_CATS_TAGGED = [{ "name": """Animal Care Supplies (Collars, Clothing, Leashes,""", "cat": """animal"""},
{ "name": """Animal Supplies""", "cat": """animal"""},
{ "name": """Cages/Shelters, Animal and Marine Life (See Class""", "cat": """animal"""},
{ "name": """Hay and Straw""", "cat": """animal"""},
{ "name": """HORSESHOE EQUIPMENT""", "cat": """animal"""},
{ "name": """Horseshoes, Horseshoe Nails, Farrier Tools, and Bl""", "cat": """animal"""},
{ "name": """Pharmaceuticals, Veterinary, Animal: Drugs, Vaccin""", "cat": """animal"""},
{ "name": """Saddles""", "cat": """animal"""},
{ "name": """Trailers, Livestock""", "cat": """animal"""},
{ "name": """ARMOR, BODY""", "cat": """armor"""},
{ "name": """ARMOR, BODY, BALLISTIC; TO PROVIDE TYPE II BALLIST""", "cat": """armor"""},
{ "name": """FACE SHIELD AND PARTS, PLASTIC""", "cat": """armor"""},
{ "name": """Police Protection Equipment (Body Armor and Riot S""", "cat": """armor"""},
{ "name": """Badges and Emblems, Metal: Cap, Game Wardens', Off""", "cat": """clothing"""},
{ "name": """Badges, Buttons, Emblems, and ID Cards, Celluloid""", "cat": """clothing"""},
{ "name": """BADGES, CAP, UNIFORM""", "cat": """clothing"""},
{ "name": """Belts, Cases, Holsters, Scabbards, etc.""", "cat": """clothing"""},
{ "name": """ALTERATIONS""", "cat": """clothing"""},
{ "name": """Athletic and Sporting Goods Equipment and Accessor""", "cat": """clothing"""},
{ "name": """ATHLETIC APPAREL: AWARD JACKETS, JERSEYS, SHOES, S""", "cat": """clothing"""},
{ "name": """Athletic Equipment and Sporting Goods and Accessor""", "cat": """clothing"""},
{ "name": """BADGES, NAME, PREPRINTED, PLASTIC, PIN-ON TYPE""", "cat": """clothing"""},
{ "name": """BELTS AND ACCESSORIES, POLICE TYPE""", "cat": """clothing"""},
{ "name": """Boots (Other Than Leather or Rubber)""", "cat": """clothing"""},
{ "name": """Boots, Leather""", "cat": """clothing"""},
{ "name": """Buckles, Belt and Clothing""", "cat": """clothing"""},
{ "name": """CAPS, BASEBALL""", "cat": """clothing"""},
{ "name": """CLOTHING ACCESSORIES (SEE CLASS 800 FOR SHOES AND""", "cat": """clothing"""},
{ "name": """CLOTHING: CAPS, HATS AND HEADWEAR""", "cat": """clothing"""},
{ "name": """CLOTHING: PANTS, SLACKS, TROUSERS, SHORTS""", "cat": """clothing"""},
{ "name": """CLOTHING: POLICE UNIFORMS""", "cat": """clothing"""},
{ "name": """CLOTHING: TROUSERS, SUPV AND UNIFORM""", "cat": """clothing"""},
{ "name": """CLOTHING: TROUSERS, WORK""", "cat": """clothing"""},
{ "name": """Clothing/clothing material""", "cat": """clothing"""},
{ "name": """COATS""", "cat": """clothing"""},
{ "name": """Coats, Jackets, Parkas, Vests  (Cold Weather)""", "cat": """clothing"""},
{ "name": """Costumes and Accessories""", "cat": """clothing"""},
{ "name": """COVERALLS, DISPOSABLE, ZIPPER FRONT, LONG SLEEVE,""", "cat": """clothing"""},
{ "name": """EMBLEMS AND INSIGNIAS, POLICE""", "cat": """clothing"""},
{ "name": """HATS, FELT, DRESS AND WORK, MEN'S""", "cat": """clothing"""},
{ "name": """INSIGNIA, COLLAR PIN""", "cat": """clothing"""},
{ "name": """JACKET""", "cat": """clothing"""},
{ "name": """JACKET SUPERSHELL EMERGENCY RESPONSE L-R""", "cat": """clothing"""},
{ "name": """JACKET SUPERSHELL EMERGENCY RESPONSE L-TALL""", "cat": """clothing"""},
{ "name": """JACKET SUPERSHELL EMERGENCY RESPONSE M-SHT""", "cat": """clothing"""},
{ "name": """JACKET SUPERSHELL EMERGENCY RESPONSE MED-R""", "cat": """clothing"""},
{ "name": """JACKET SUPERSHELL EMERGENCY RESPONSE SM-R""", "cat": """clothing"""},
{ "name": """JACKET SUPERSHELL EMERGENCY RESPONSE SM-SHT""", "cat": """clothing"""},
{ "name": """JACKET SUPERSHELL EMERGENCY RESPONSE XL-R""", "cat": """clothing"""},
{ "name": """JACKET SUPERSHELL EMERGENCY RESPONSE XL-TALL""", "cat": """clothing"""},
{ "name": """JACKETS, ALL WEATHER""", "cat": """clothing"""},
{ "name": """JACKETS, RAIN, POLICE""", "cat": """clothing"""},
{ "name": """JACKETS, WINDBREAKER STYLE, POLYESTER/COTTON BLEND""", "cat": """clothing"""},
{ "name": """JERSEYS, FOOTBALL, 3/4 LENGTH SLEEVES""", "cat": """clothing"""},
{ "name": """JEWELRY, UNIFORM""", "cat": """clothing"""},
{ "name": """LAPEL PINS, WITH ACCESSORY DESIGN""", "cat": """clothing"""},
{ "name": """Leather, Belt""", "cat": """clothing"""},
{ "name": """PANTS AND SHORTS, CARGO""", "cat": """clothing"""},
{ "name": """PANTS, BUNKER, FIREFIGHTER, 7 OZ. NOMEX, W/MOISTUR""", "cat": """clothing"""},
{ "name": """PANTS, UNIFORM, ELASTIC, 65% POLYESTER, 35% COMBED""", "cat": """clothing"""},
{ "name": """PANTS, UNIFORM, POLICE AND FIRE""", "cat": """clothing"""},
{ "name": """PATCH 2 CHEVRON W/STAR CORPORAL NAVY AND GRAY""", "cat": """clothing"""},
{ "name": """PATCH 2 CHEVRON W/STAR CORPORAL SUBDUED GREEN""", "cat": """clothing"""},
{ "name": """PATCH 3 CHEVRON SERGEANT NAVY AND GRAY""", "cat": """clothing"""},
{ "name": """PATCH 3 CHEVRON SERGEANT SUBDUED GREEN""", "cat": """clothing"""},
{ "name": """PATCH 3 SR. SERGEANT CHEVRON NAVY AND GRAY""", "cat": """clothing"""},
{ "name": """Patch Any Dept Patch Reduced In Sz for Placement  Cap Max3""", "cat": """clothing"""},
{ "name": """PATCH APD HASH MARK 9 BAR NAVY AND GRAY""", "cat": """clothing"""},
{ "name": """PATCH AUSTIN POLICE BADGE GREEN""", "cat": """clothing"""},
{ "name": """PATCH AUSTIN POLICE BADGE SILVER""", "cat": """clothing"""},
{ "name": """Patch Collar Insignia 1 bar Lieutenant Nvy & Gray""", "cat": """clothing"""},
{ "name": """Patch Collar Insignia 1 Bar Lieutenant Subdued Green""", "cat": """clothing"""},
{ "name": """Patch Collar Insignia 1 Star Commander Nvy & Gray""", "cat": """clothing"""},
{ "name": """Patch Collar Insignia 1 Star Commander Subdued Green""", "cat": """clothing"""},
{ "name": """Patch Collar Insignia 2 Star Commander Nvy & Gray""", "cat": """clothing"""},
{ "name": """Patch Collar Insignia 3 Star Commander Nvy & Gray""", "cat": """clothing"""},
{ "name": """Patch Explorer silver/navy""", "cat": """clothing"""},
{ "name": """PATCH POLICE BOMB SQUAD SUBDUED GREEN""", "cat": """clothing"""},
{ "name": """PATCH POLICE CAPITAL OF TEXAS SUBDUED GREEN""", "cat": """clothing"""},
{ "name": """PATCH POLICE CHAPLAIN NAVY AND GRAY""", "cat": """clothing"""},
{ "name": """PATCH POLICE CINT SUBDUED GREEN""", "cat": """clothing"""},
{ "name": """PATCH POLICE DEPT SHOULDER NAVY AND GRAY""", "cat": """clothing"""},
{ "name": """PATCH POLICE FORENSICS NAVY AND GRAY""", "cat": """clothing"""},
{ "name": """PATCH POLICE K-9 PATROL SUBDUED GREEN""", "cat": """clothing"""},
{ "name": """PATCH POLICE SWAT SUBDUED GREEN""", "cat": """clothing"""},
{ "name": """PATCHS SENIOR SERGEANT CHEVRON in OD Green""", "cat": """clothing"""},
{ "name": """RAIN WEAR""", "cat": """clothing"""},
{ "name": """RAINCOATS""", "cat": """clothing"""},
{ "name": """Sewing and Alteration Services""", "cat": """clothing"""},
{ "name": """SHIRT GOLF 100% COA LOGO GREY LARGE""", "cat": """clothing"""},
{ "name": """SHIRT GOLF 100% COA LOGO GREY XLARGE""", "cat": """clothing"""},
{ "name": """SHIRT GOLF 50/50 2XLRG  GENERAL""", "cat": """clothing"""},
{ "name": """SHIRT GOLF 50/50 SMALL - XLARGE GENERAL""", "cat": """clothing"""},
{ "name": """SHIRT GOLF COA LOGO BLACK 2XL""", "cat": """clothing"""},
{ "name": """SHIRT GOLF COA LOGO BLACK MEDIUM""", "cat": """clothing"""},
{ "name": """SHIRT GOLF COA LOGO BLACK SMALL""", "cat": """clothing"""},
{ "name": """SHIRT GOLF COA LOGO BLACK XLARGE""", "cat": """clothing"""},
{ "name": """SHIRT GOLF COA LOGO NAVY 2XLARGE""", "cat": """clothing"""},
{ "name": """SHIRT GOLF COA LOGO NAVY LARGE""", "cat": """clothing"""},
{ "name": """SHIRT GOLF COA LOGO NAVY XLARGE""", "cat": """clothing"""},
{ "name": """SHIRT GOLF COA LOGO RED LARGE""", "cat": """clothing"""},
{ "name": """SHIRT GOLF COA LOGO ROYAL BLUE MEDIUM""", "cat": """clothing"""},
{ "name": """SHIRT GOLF COA LOGO ROYAL BLUE XL""", "cat": """clothing"""},
{ "name": """Shirt Uniform""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM APD TACTICAL L/S 65/35 POLY/COT 2XL-LONG""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM APD TACTICAL L/S 65/35 POLY/COT 2XL-REG""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM APD TACTICAL L/S 65/35 POLY/COT LARGE-LONG""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM APD TACTICAL L/S 65/35 POLY/COT LARGE-REG""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM APD TACTICAL L/S 65/35 POLY/COT MED-LONG""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM APD TACTICAL L/S 65/35 POLY/COT MED-REG""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM APD TACTICAL L/S 65/35 POLY/COT MED-SHORT""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM APD TACTICAL L/S 65/35 POLY/COT NOSTOCK#1""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM APD TACTICAL L/S 65/35 POLY/COT NOSTOCK#2""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM APD TACTICAL L/S 65/35 POLY/COT NOSTOCK#3""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM APD TACTICAL L/S 65/35 POLY/COT NOSTOCK#4""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM APD TACTICAL L/S 65/35 POLY/COT NOSTOCK#5""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM APD TACTICAL L/S 65/35 POLY/COT NOSTOCK#6""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM APD TACTICAL L/S 65/35 POLY/COT SM-REG""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM APD TACTICAL L/S 65/35 POLY/COT SM-SHORT""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM APD TACTICAL L/S 65/35 POLY/COT XL-LONG""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM APD TACTICAL L/S 65/35 POLY/COT XL-REG""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM L/S  APD NAVY NON STOCK SIZE""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM L/S APD NAVY SZ 14-1/2 X 34""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM L/S APD NAVY SZ 15 X 32""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM L/S APD NAVY SZ 15 X 33""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM L/S APD NAVY SZ 15 X 35""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM L/S APD NAVY SZ 15-1/2 X 32""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM L/S APD NAVY SZ 15-1/2 X 33""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM L/S APD NAVY SZ 15-1/2 X 34""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM L/S APD NAVY SZ 15-1/2 X 35""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM L/S APD NAVY SZ 16 X 34""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM L/S APD NAVY SZ 16 X 35""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM L/S APD NAVY SZ 16-1/2 X 32""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM L/S APD NAVY SZ 16-1/2 X 34""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM L/S APD NAVY SZ 16-1/2 X 35""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM L/S APD NAVY SZ 16-1/2 X 36""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM L/S APD NAVY SZ 17 X 35""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM L/S APD NAVY SZ 17 X 36""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM L/S APD NAVY SZ 17-1/2 X 35""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM L/S APD NAVY SZ 17-1/2 X 36/37""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM L/S APD NAVY SZ 17-1/2 X 37""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM L/S APD NAVY SZ 18 X 37""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM L/S APD NAVY SZ 18-1/2 X 35""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM L/S APD NAVY SZ 19-19.5 X 36-37""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM L/S APD NAVY SZ 19-19.5x35""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM LADIES L/S APD NAVY SZ 32""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM LADIES L/S APD NAVY SZ 38""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM S/S APD NAVY 2XL 18.5""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM S/S APD NAVY 3XL 19.5""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM S/S APD NAVY 4XL 20""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM S/S APD NAVY LADY LRG 40""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM S/S APD NAVY LADY MED 35/36""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM S/S APD NAVY LADY SM 33/34""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM S/S APD NAVY LADY XSM 31/32""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM S/S APD NAVY LRG 16.5""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM S/S APD NAVY MED 15.5""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM S/S APD NAVY SM 14.5""", "cat": """clothing"""},
{ "name": """SHIRT UNIFORM S/S APD NAVY XLRG 17.5""", "cat": """clothing"""},
{ "name": """SHIRTS""", "cat": """clothing"""},
{ "name": """SHIRTS, DRESS, MEN'S, 65% POLYESTER, 35% COTTON BL""", "cat": """clothing"""},
{ "name": """SHIRTS, FATIGUE, MEN'S AND WOMEN'S, POLY/COTTON, P""", "cat": """clothing"""},
{ "name": """SHIRTS, GOLF""", "cat": """clothing"""},
{ "name": """SHIRTS, GOLF, POLO TYPE, JERSEY KNIT, LONG SLEEVE""", "cat": """clothing"""},
{ "name": """SHIRTS, LONG SLEEVE, UNIFORM, MALE, 100% POLYESTER""", "cat": """clothing"""},
{ "name": """SHIRTS, LONG SLEEVE, UNIFORM, MALE, POLY/COTTON BL""", "cat": """clothing"""},
{ "name": """SHIRTS, PULLOVER, TURTLENECK, 100% COTTON""", "cat": """clothing"""},
{ "name": """SHIRTS, SHORT SLEEVE, UNIFORM, MALE, 100% POLYESTE""", "cat": """clothing"""},
{ "name": """SHIRTS, SPORT TYPE, BOYS AND MENS""", "cat": """clothing"""},
{ "name": """SHIRTS, TEE (T), MESH COMFORT, SHORT SLEEVE, TRADI""", "cat": """clothing"""},
{ "name": """SHIRTS, TEE, MENS. MADE OF LONG STAPLE COTTON YARN""", "cat": """clothing"""},
{ "name": """SHIRTS, UNIFORM, MEN'S, LONG SLEEVE, POLY/COTTON B""", "cat": """clothing"""},
{ "name": """SHIRTS, UNIFORM, MEN'S, SHORT SLEEVE, POLY/COTTON""", "cat": """clothing"""},
{ "name": """SHIRTS, WORK, MEN'S AND WOMEN'S, LONG SLEEVE, FLAM""", "cat": """clothing"""},
{ "name": """Shoe Repair Supplies: Beading, Belting, Cleats, El""", "cat": """clothing"""},
{ "name": """SHOES AND BOOTS""", "cat": """clothing"""},
{ "name": """SHORTS, ATHLETIC, ELASTIC WAIST""", "cat": """clothing"""},
{ "name": """Silk Screened Shirts, Jackets, Hats, etc.""", "cat": """clothing"""},
{ "name": """SPORTING GOODS, ATHLETIC EQUIPMENT AND ATHLETIC FA""", "cat": """clothing"""},
{ "name": """SUITS, RAIN, INCL. JACKET, OVERALL PANTS, AND DETA""", "cat": """clothing"""},
{ "name": """SWEATSHIRTS, 50% POLYESTER, 50% COTTON, FLEECE""", "cat": """clothing"""},
{ "name": """SWEATSHIRTS, 50% POLYESTER, 50% COTTON, MEDIUM WEI""", "cat": """clothing"""},
{ "name": """SWEATSHIRTS, LONG SLEEVE, HOODED, 50% POLYESTER OR""", "cat": """clothing"""},
{ "name": """trouser""", "cat": """clothing"""},
{ "name": """TROUSERS APD MEN SIZE 32""", "cat": """clothing"""},
{ "name": """TROUSERS APD MEN SIZE 33""", "cat": """clothing"""},
{ "name": """TROUSERS APD MEN SIZE 34""", "cat": """clothing"""},
{ "name": """TROUSERS APD MEN SIZE 35""", "cat": """clothing"""},
{ "name": """TROUSERS APD MEN SIZE 36""", "cat": """clothing"""},
{ "name": """TROUSERS APD MEN SIZE 38""", "cat": """clothing"""},
{ "name": """TROUSERS APD MEN SIZE 40""", "cat": """clothing"""},
{ "name": """TROUSERS APD MEN SIZE 42""", "cat": """clothing"""},
{ "name": """TROUSERS APD MEN SIZE 44""", "cat": """clothing"""},
{ "name": """Trousers Uniform""", "cat": """clothing"""},
{ "name": """TROUSERS, STRETCH, MALE, 100% FORTREL POLYESTER ST""", "cat": """clothing"""},
{ "name": """TROUSERS, UNIFORM, MALE""", "cat": """clothing"""},
{ "name": """UNDERSHIRTS, MEN'S, T-SHIRT STYLE""", "cat": """clothing"""},
{ "name": """Uniform Rental or Lease""", "cat": """clothing"""},
{ "name": """Uniforms, Blended Fabric""", "cat": """clothing"""},
{ "name": """Work Clothes""", "cat": """clothing"""},
{ "name": """Unmanned Aerial Vehicles (UAV), Drones""", "cat": """drone"""},
{ "name": """Explosives, Grenades, Accessories and Supplies""", "cat": """explosives"""},
{ "name": """EXPLOSIVES, LIQUID AND SOLID""", "cat": """explosives"""},
{ "name": """Explosives/blasting""", "cat": """explosives"""},
{ "name": """Alcohol and Drug Testing Services""", "cat": """forensics"""},
{ "name": """ALCOHOLS, ISOPROPYL""", "cat": """forensics"""},
{ "name": """Analyzers and Accessories""", "cat": """forensics"""},
{ "name": """BAGS, BIOHAZARD, INFECTIOUS WASTE""", "cat": """forensics"""},
{ "name": """BAGS, PLASTIC, DISPOSABLE""", "cat": """forensics"""},
{ "name": """BAGS, PLASTIC, STORAGE, WRITE-ON""", "cat": """forensics"""},
{ "name": """BAGS, PLASTIC, ZIPLOCK""", "cat": """forensics"""},
{ "name": """BAGS, POLY, ZIP LOCK""", "cat": """forensics"""},
{ "name": """Balances and Accessories""", "cat": """forensics"""},
{ "name": """BALANCES, ELECTRONIC, LABORATORY""", "cat": """forensics"""},
{ "name": """BEAKERS (LABORATORY GLASSWARE)""", "cat": """forensics"""},
{ "name": """Biochemical Reagents and Tests: Antibiotic Assays,""", "cat": """forensics"""},
{ "name": """Biochemical Research Equipment: DNA Synthesizers,""", "cat": """forensics"""},
{ "name": """Biological Testing Services""", "cat": """forensics"""},
{ "name": """BLOOD GROUP SUBSTANCES""", "cat": """forensics"""},
{ "name": """BLOOD TESTING SERVICES""", "cat": """forensics"""},
{ "name": """BOOKS, LAB""", "cat": """forensics"""},
{ "name": """BOTTLES AND LIDS, SPECIMEN, PLASTIC""", "cat": """forensics"""},
{ "name": """BOTTLES, POLYPROPYLENE, GENERAL USE""", "cat": """forensics"""},
{ "name": """BOTTLES, SAMPLE, ASPIRATOR, CENTRIFUGE, DROPPING (""", "cat": """forensics"""},
{ "name": """Breath Alcohol Testing Instruments and Supplies""", "cat": """forensics"""},
{ "name": """BULBS (LABORATORY GLASSWARE)""", "cat": """forensics"""},
{ "name": """CALIBRATION KITS, VOLUME, PIPETTER""", "cat": """forensics"""},
{ "name": """CELLULOSE DERIVATIVES""", "cat": """forensics"""},
{ "name": """Centrifuges, Desk Top and Free Standing""", "cat": """forensics"""},
{ "name": """CHEMICAL LABORATORY EQUIPMENT AND SUPPLIES""", "cat": """forensics"""},
{ "name": """Chemicals""", "cat": """forensics"""},
{ "name": """CHEMICALS, LABORATORY - LIQUID (A-G)""", "cat": """forensics"""},
{ "name": """Chemicals, Laboratory (ACS, CP, Practical, Reagent""", "cat": """forensics"""},
{ "name": """CHEMICALS, LABORATORY, REAGENTS""", "cat": """forensics"""},
{ "name": """CHEMICALS, MISCELLANEOUS PHOTOGRAPHIC, BRAND LISTE""", "cat": """forensics"""},
{ "name": """Chemicals, Photographic""", "cat": """forensics"""},
{ "name": """Chillers, Heat Exchangers and Receivers""", "cat": """forensics"""},
{ "name": """CHROMATOGRAPH ACCESSORIES AND SUPPLIES""", "cat": """forensics"""},
{ "name": """Chromatographs, Gas""", "cat": """forensics"""},
{ "name": """Chromatographs, Liquid: High-Performance (HPLC), P""", "cat": """forensics"""},
{ "name": """Chromatography Supplies: Developing Tanks, Columns""", "cat": """forensics"""},
{ "name": """Cleaning Equipment and Supplies, Laboratory""", "cat": """forensics"""},
{ "name": """COLUMNS AND CONDENSERS (LABORATORY GLASSWARE)""", "cat": """forensics"""},
{ "name": """COLUMNS, GAS CHROMATOGRAPHY/MASS SPECTROPHOTOMETRY""", "cat": """forensics"""},
{ "name": """Condensing Units""", "cat": """forensics"""},
{ "name": """Counterfeit Scanning Devices""", "cat": """forensics"""},
{ "name": """CRYSTALS, POLYMER""", "cat": """forensics"""},
{ "name": """DISPOSAL CONTAINER FOR NEEDLES, PLASTIC""", "cat": """forensics"""},
{ "name": """Drug Assay and Screening Test Kits (Except Radioim""", "cat": """forensics"""},
{ "name": """ETHANOL""", "cat": """forensics"""},
{ "name": """Evaporators, Analytical (Air or Nitrogen Jet)""", "cat": """forensics"""},
{ "name": """Evidence Bags, Containers and Supplies""", "cat": """forensics"""},
{ "name": """EVIDENCE COLLECTION KITS""", "cat": """forensics"""},
{ "name": """Examination and Testing""", "cat": """forensics"""},
{ "name": """EXTRACTION EQUIPMENT AND PARTS, LABORATORY""", "cat": """forensics"""},
{ "name": """FILTER ELEMENTS, PRE-CLEANER - BRAND LISTED OR EQU""", "cat": """forensics"""},
{ "name": """FILTER PAPER, PH""", "cat": """forensics"""},
{ "name": """FILTERS, SPIRIT DUPLICATING""", "cat": """forensics"""},
{ "name": """Fingerprinting Equipment, Accessories, and Supplie""", "cat": """forensics"""},
{ "name": """Forensic Engineering""", "cat": """forensics"""},
{ "name": """Forensic Equipment Maintenance and Repair""", "cat": """forensics"""},
{ "name": """FREEZERS""", "cat": """forensics"""},
{ "name": """FREEZERS, UPRIGHT, GENERAL PURPOSE, LABORATORY""", "cat": """forensics"""},
{ "name": """Fume Hoods, Laminar Flow Hoods, Biological Cabinet""", "cat": """forensics"""},
{ "name": """Furniture, Laboratory (Custom Made)""", "cat": """forensics"""},
{ "name": """Gas Chromatagh Systems Maintenance and Repair""", "cat": """forensics"""},
{ "name": """Generators, X-Ray""", "cat": """forensics"""},
{ "name": """Genetic Parentage Testing Services (DNA)""", "cat": """forensics"""},
{ "name": """Gloves and Finger Cots, Medical Type""", "cat": """forensics"""},
{ "name": """GLOVES, INDUSTRIAL TYPE, RESISTANT TO ACID, FIRE,""", "cat": """forensics"""},
{ "name": """GLOVES, NITRILE, SOLVENT/CHEMICAL RESISTANT""", "cat": """forensics"""},
{ "name": """Group Auditory Systems, Language Laboratories, and""", "cat": """forensics"""},
{ "name": """HOT PLATES, LABORATORY""", "cat": """forensics"""},
{ "name": """Image Analysis Systems""", "cat": """forensics"""},
{ "name": """KITS, TEST""", "cat": """forensics"""},
{ "name": """LAB EQUIP,  ACCY SUPPLIES: BIOCHEM, CHEM, SCIENCE, ETC.""", "cat": """forensics"""},
{ "name": """LABORATORY ANALYSIS AND TESTING OF VARIOUS TYPES O""", "cat": """forensics"""},
{ "name": """LABORATORY ANALYSIS SERVICES, HUMAN DNA""", "cat": """forensics"""},
{ "name": """LABORATORY AND FIELD EQUIPMENT AND SUPPLIES: BIOLO""", "cat": """forensics"""},
{ "name": """Laboratory and Field Testing Services (Not Otherwi""", "cat": """forensics"""},
{ "name": """Laboratory and Scientific Equipment and Supplies (Not Otherw""", "cat": """forensics"""},
{ "name": """Laboratory Equipment and Accessories, Maintenance""", "cat": """forensics"""},
{ "name": """LABORATORY EQUIPMENT AND ACCESSORIES: BIOCHEMISTRY""", "cat": """forensics"""},
{ "name": """Laboratory Equipment and Accessories: Specialized,""", "cat": """forensics"""},
{ "name": """Laboratory Equipment, General""", "cat": """forensics"""},
{ "name": """Laboratory Gases: Argon, Carbon Dioxide, Helium, H""", "cat": """forensics"""},
{ "name": """LABORATORY SUPPLIES PER PRICE AGREEMENT""", "cat": """forensics"""},
{ "name": """Laboratory Supplies: Asbestos Squares, Corks, File""", "cat": """forensics"""},
{ "name": """Lamps and Lights, Dental: Operating, Ultraviolet,""", "cat": """forensics"""},
{ "name": """MAINTENANCE AND REPAIR, LABORATORY EQUIPMENT, INCLUDING PART""", "cat": """forensics"""},
{ "name": """MANIFOLDS, VACUUM, STAINLESS STEEL, AUTOCLAVABLE""", "cat": """forensics"""},
{ "name": """MASKS, SURGICAL""", "cat": """forensics"""},
{ "name": """MASKS, SURGICAL, DISPOSABLE, "NON-FIBERGLASS" FILT""", "cat": """forensics"""},
{ "name": """Mass Spectrometers and Accessories""", "cat": """forensics"""},
{ "name": """MEDICAL, DENTAL AND LAB SUPPLY PER PRICE AGREEMENT""", "cat": """forensics"""},
{ "name": """MICROFICHE AND MICROFILM EQUIPMENT, ACCY, AND SUPPLIES""", "cat": """forensics"""},
{ "name": """Microscope Accessories: Adapters, Condensers, Filt""", "cat": """forensics"""},
{ "name": """Microscopes, All Types (For Electron See 490-29, a""", "cat": """forensics"""},
{ "name": """PAPER, EXAMINATION TABLE""", "cat": """forensics"""},
{ "name": """Photographic Equipment (Not Including Graphic Arts""", "cat": """forensics"""},
{ "name": """Physiological Testing and Recording Equipment (Sin""", "cat": """forensics"""},
{ "name": """PIPETS, BLOOD DILUTING AND MEASURING (LABORATORY G""", "cat": """forensics"""},
{ "name": """PIPETS, SEROLOGICAL  AND VOLUMETRIC (LABORATORY GL""", "cat": """forensics"""},
{ "name": """PIPETTER REPLACEMENT PARTS""", "cat": """forensics"""},
{ "name": """Pipetters and Dispensers""", "cat": """forensics"""},
{ "name": """Polygraph Testing Services""", "cat": """forensics"""},
{ "name": """PROCESSOR, FILM AND LITH PAPER""", "cat": """forensics"""},
{ "name": """Pumps, Descaling Acid""", "cat": """forensics"""},
{ "name": """REAGENTS, BIOCHEMICAL""", "cat": """forensics"""},
{ "name": """REAGENTS, DNA FORENSIC ANALYSIS""", "cat": """forensics"""},
{ "name": """RECORDERS, TEMPERATURE, DATA LOGGER""", "cat": """forensics"""},
{ "name": """Refrigerators and Freezers, Commercial""", "cat": """forensics"""},
{ "name": """SCALES, LABORATORY BALANCE""", "cat": """forensics"""},
{ "name": """Scanners, Film, Environmentally Certified""", "cat": """forensics"""},
{ "name": """SEPTA DISKS, SILICONE RUBBER, PTFE FACED, AUTOCLAV""", "cat": """forensics"""},
{ "name": """Serums, Toxoids, and Vaccines""", "cat": """forensics"""},
{ "name": """SOLVENTS, STODDARD""", "cat": """forensics"""},
{ "name": """Spectrophotometers, Ultraviolet and Visible""", "cat": """forensics"""},
{ "name": """Syringes, Laboratory, Manual and Automatic""", "cat": """forensics"""},
{ "name": """TAPE, FINGERPRINTING LIFT TAPE""", "cat": """forensics"""},
{ "name": """Test Equipment and Supplies: Criminology Kits, Met""", "cat": """forensics"""},
{ "name": """Test Kits and Supplies, Chemistry (Not Otherwise Classified)""", "cat": """forensics"""},
{ "name": """TESTING AND CALIBRATION SERVICES""", "cat": """forensics"""},
{ "name": """Testing and Recording Instruments""", "cat": """forensics"""},
{ "name": """TESTING SERVICES""", "cat": """forensics"""},
{ "name": """TESTS, BREATH/ALCOHOL""", "cat": """forensics"""},
{ "name": """TESTS, CLINICAL LABORATORY, NON-DRUG SCREENING""", "cat": """forensics"""},
{ "name": """Thermometers and Gauges""", "cat": """forensics"""},
{ "name": """THERMOMETERS, DIGITAL IR""", "cat": """forensics"""},
{ "name": """Trauma Packs and Kits""", "cat": """forensics"""},
{ "name": """TRICONTINENTS, ABBOTT LAB KITS OR EQUAL""", "cat": """forensics"""},
{ "name": """Tubes, Electron Multiplier and Photomultiplier; an""", "cat": """forensics"""},
{ "name": """Vacuum Equipment, Laboratory, (Not Otherwise Classified)""", "cat": """forensics"""},
{ "name": """VIALS, DISPOSABLE, LABORATORY GLASSWARE""", "cat": """forensics"""},
{ "name": """X-RAY AND OTHER RADIOLOGICAL EQUIPMENT AND SUPPLIE""", "cat": """forensics"""},
{ "name": """X-Ray Equipment Maintenance and Repair""", "cat": """forensics"""},
{ "name": """GASOLINE, JET FUEL""", "cat": """helicopter"""},
{ "name": """Ammunition""", "cat": """guns"""},
{ "name": """AMMUNITION - CARTRIDGES, BLANK""", "cat": """guns"""},
{ "name": """AMMUNITION, TRAINING""", "cat": """guns"""},
{ "name": """Gun Cleaning Supplies: Patches, Rods, Silicone Clo""", "cat": """guns"""},
{ "name": """Guns, Machine (Including Other Military Style Weap""", "cat": """guns"""},
{ "name": """Guns, Pistols, Rifles, and Shotguns""", "cat": """guns"""},
{ "name": """MAGAZINES, PISTOL""", "cat": """guns"""},
{ "name": """PARTS AND ACCESSORIES,: GUN, RIFLE, PISTOL AND SHOTGUN""", "cat": """guns"""},
{ "name": """PROJECTILES, PRACTICE""", "cat": """guns"""},
{ "name": """Rifle Range Equipment Maintenance and Repair""", "cat": """guns"""},
{ "name": """SCOPES, PISTOL AND RIFLE""", "cat": """guns"""},
{ "name": """Scopes, Rifle and Range""", "cat": """guns"""},
{ "name": """Targets, Pasters, Rifle Range Equip, Mobile Shooting Range""", "cat": """guns"""},
{ "name": """TARGETS, POLICE""", "cat": """guns"""},
{ "name": """Tools, Gunsmith's: Borescopes, etc.""", "cat": """guns"""},
{ "name": """Weapon Maintenance and Repair""", "cat": """guns"""},
{ "name": """AIRCRAFT AND AIRPORT, EQUIPMENT, PARTS, AND SUPPLI""", "cat": """helicopter"""},
{ "name": """Aircraft and Aviation Parts, Equipment""", "cat": """helicopter"""},
{ "name": """AIRCRAFT OPERATIONS SERVICES""", "cat": """helicopter"""},
{ "name": """Airplane/Helicopter Services (Not Otherwise Classi""", "cat": """helicopter"""},
{ "name": """Airplanes, Helicopters and Accessories Maint. and Repair""", "cat": """helicopter"""},
{ "name": """Airplanes, Helicopters, and Accessories Maintenanc""", "cat": """helicopter"""},
{ "name": """Aviation Insurance""", "cat": """helicopter"""},
{ "name": """AVIONICS, MAINTENANCE AND REPAIR""", "cat": """helicopter"""},
{ "name": """Engines and Parts, Helicopter""", "cat": """helicopter"""},
{ "name": """Gasoline, Aviation (Including Jet Fuel)""", "cat": """helicopter"""},
{ "name": """Helicopters""", "cat": """helicopter"""},
{ "name": """Instruments and Testers, Airplane""", "cat": """helicopter"""},
{ "name": """Instruments and Testers, Helicopter""", "cat": """helicopter"""},
{ "name": """Oil, Aviation Engine""", "cat": """helicopter"""},
{ "name": """Parts (Except Engine), Helicopter""", "cat": """helicopter"""},
{ "name": """PARTS AND ACCESSORIES, HELICOPTER""", "cat": """helicopter"""},
{ "name": """Tools, Helicopter""", "cat": """helicopter"""},
{ "name": """Bond/Theft/Prof Liab Insurance""", "cat": """insurance"""},
{ "name": """Bond/theft/prof liab Insurance""", "cat": """insurance"""},
{ "name": """INSURANCE AND RISK MANAGEMENT""", "cat": """insurance"""},
{ "name": """Insurance-bond/theft/prof l""", "cat": """insurance"""},
{ "name": """INSURANCE, ALL TYPES""", "cat": """insurance"""},
{ "name": """Liability, General Insurance""", "cat": """insurance"""},
{ "name": """ACCESSORIES FOR LAPTOP COMPUTER""", "cat": """it_hardware"""},
{ "name": """ADAPTERS, COMPUTER CABLE""", "cat": """it_hardware"""},
{ "name": """AMPLIFIERS, RADIO FREQUENCY""", "cat": """it_hardware"""},
{ "name": """Audio Equipment and Accessories, Television, Microphones, Mi""", "cat": """it_hardware"""},
{ "name": """Audio Visual Equipment and Supplies (Not Otherwise""", "cat": """it_hardware"""},
{ "name": """Audio/Video Equipment and Accessory Rental or Leas""", "cat": """it_hardware"""},
{ "name": """Audio/Video Production Services Complete""", "cat": """it_hardware"""},
{ "name": """Batteries, Dry Cell (Except Communications Radio a""", "cat": """it_hardware"""},
{ "name": """BATTERIES, LITHIUM, DIGITAL CAMERAS""", "cat": """it_hardware"""},
{ "name": """BATTERY CHARGERS AND BATTERIES, DIGITAL CAMERAS""", "cat": """it_hardware"""},
{ "name": """BATTERY PACKS FOR ELECTRONIC EQUIPMENT""", "cat": """it_hardware"""},
{ "name": """Cable Shielded, Gel-Filled CAT5E F/UTP""", "cat": """it_hardware"""},
{ "name": """CABLE, COMPUTER, MISC.""", "cat": """it_hardware"""},
{ "name": """Camera Accessories: Batteries, Exposure Meters (Li""", "cat": """it_hardware"""},
{ "name": """Cameras, Digital, For Windows""", "cat": """it_hardware"""},
{ "name": """Cameras, Video, Portable, Body and Dash Cams""", "cat": """it_hardware"""},
{ "name": """CARDS, ADAPTER, MEMORY""", "cat": """it_hardware"""},
{ "name": """CELLULAR PHONES, COMPLETE UNITS (BRAND LISTED OR E""", "cat": """it_hardware"""},
{ "name": """Citation Issuance Devices and Supplies""", "cat": """it_hardware"""},
{ "name": """Communications: Networking, Linking, etc.""", "cat": """it_hardware"""},
{ "name": """COMPUTER ACCESSORIES AND SUPPLIES, ENVIRONMENTALLY CERTIFIED""", "cat": """it_hardware"""},
{ "name": """Computers, Data Processing Equipment, Maintenance and Repair""", "cat": """it_hardware"""},
{ "name": """Drives, Compact Disk (CD ROM, etc.)""", "cat": """it_hardware"""},
{ "name": """ELECTRONIC COMPONENTS, REPLACEMENT PARTS, AND ACCE""", "cat": """it_hardware"""},
{ "name": """Keyboard Dust Covers, Key Top Covers, Keyboard Dra""", "cat": """it_hardware"""},
{ "name": """MAINTENANCE AND REPAIR, AUDIO/VIDEO EQUIPMENT""", "cat": """it_hardware"""},
{ "name": """Maintenance-computer hardware""", "cat": """it_hardware"""},
{ "name": """MAINTENANCE, MICRO-COMPUTER HARDWARE AND PERIHERAL""", "cat": """it_hardware"""},
{ "name": """Minor computer hardware""", "cat": """it_hardware"""},
{ "name": """Monitors, Color and Monochrome, Environmentally Certified""", "cat": """it_hardware"""},
{ "name": """MOTHERBOARDS, MICROCOMPUTER""", "cat": """it_hardware"""},
{ "name": """PARTS & ACCESSORIES, CELLULAR PHONES""", "cat": """it_hardware"""},
{ "name": """PARTS AND ACCESSORIES, CAMERAS, DIGITAL""", "cat": """it_hardware"""},
{ "name": """PARTS AND ACCESSORIES, RADIO, MISC. (BRAND LISTED""", "cat": """it_hardware"""},
{ "name": """Peripherals, Miscellaneous: Joy Sticks, Graphic Di""", "cat": """it_hardware"""},
{ "name": """Photo Identification Systems, Complete""", "cat": """it_hardware"""},
{ "name": """Plotters, Graphic""", "cat": """it_hardware"""},
{ "name": """POINTERS, INFRARED, FOR USE ON LCD PANELS""", "cat": """it_hardware"""},
{ "name": """Projection Screens, Standard and Rear-Projection T""", "cat": """it_hardware"""},
{ "name": """Projectors, Filmstrip (Standard Types Only); Carry""", "cat": """it_hardware"""},
{ "name": """RACKS, MOUNTING, FOR MODEMS""", "cat": """it_hardware"""},
{ "name": """Radio/Telecommunications/Telephone Equipment (Incl""", "cat": """it_hardware"""},
{ "name": """Recorders, Digital, Voice to CD""", "cat": """it_hardware"""},
{ "name": """Repair Equipment, Electronic: Cleaning, Desolderin""", "cat": """it_hardware"""},
{ "name": """REWINDER AND REWINDER CLEANER, VHS TAPE""", "cat": """it_hardware"""},
{ "name": """Scanners and Readers, Optical Character: Bar Code,""", "cat": """it_hardware"""},
{ "name": """Scanners, Document: Handheld, Desktop and High Vol""", "cat": """it_hardware"""},
{ "name": """Security Systems and Equipment, Communications""", "cat": """it_hardware"""},
{ "name": """SERVERS, FILE, MICROCOMPUTER, Environmentally Certified""", "cat": """it_hardware"""},
{ "name": """Telephone Switching (PBX) Systems""", "cat": """it_hardware"""},
{ "name": """Television Equipment and Accessories (Including Vi""", "cat": """it_hardware"""},
{ "name": """Television Receivers and Consoles""", "cat": """it_hardware"""},
{ "name": """UNINTERRUPTIBLE POWER SUPPLY, COMPUTER""", "cat": """it_hardware"""},
{ "name": """VCR/DVD/Television Combinations""", "cat": """it_hardware"""},
{ "name": """Video Camera-Recorders, Accessories and Parts (Por""", "cat": """it_hardware"""},
{ "name": """VIDEO CAMERA, VHS-C COMPACT CONSUMER CAMCORDER, FU""", "cat": """it_hardware"""},
{ "name": """VIDEO RECORDER, VCR, PROFESSIONAL GRADE, VHS LEVEL""", "cat": """it_hardware"""},
{ "name": """Video Systems (For Studio Quality Production)""", "cat": """it_hardware"""},
{ "name": """Video/Disk/DVD Players (Recorders and Playback Only Devices)""", "cat": """it_hardware"""},
{ "name": """COMPUTER ACCESSORIES AND SUPPLIES""", "cat": """it_hardware"""},
{ "name": """Application, Infrastructure, Hosting and Cloud Computing Ser""", "cat": """it_software"""},
{ "name": """Computer Software""", "cat": """it_software"""},
{ "name": """GIS SOFTWARE PRE-PACKAGED""", "cat": """it_software"""},
{ "name": """GLOBAL POSITIONING SYSTEM""", "cat": """it_software"""},
{ "name": """Interactive Voice Response (IVR) Systems""", "cat": """it_software"""},
{ "name": """INTERNET DATABASE SUBSCRIPTIONS""", "cat": """it_software"""},
{ "name": """Mapping Services (See 920-33 for Digitized Mapping""", "cat": """it_software"""},
{ "name": """Mapping Services, Digitized (See 962-52 for Standa""", "cat": """it_software"""},
{ "name": """Project Management Software""", "cat": """it_software"""},
{ "name": """SUBSCRIPTIONS, SOFTWARE LICENSING, CLOUD BASED""", "cat": """it_software"""},
{ "name": """Support Services, Computer""", "cat": """it_software"""},
{ "name": """Surveying Systems, Geo/Satellite Navigation Type""", "cat": """it_software"""},
{ "name": """BATTERIES FOR ELECTRONIC EQUIPMENT (ALKALINE)""", "cat": """it_hardware"""},
{ "name": """BATTERIES FOR ELECTRONIC EQUIPMENT (LITHIUM)""", "cat": """it_hardware"""},
{ "name": """BATTERIES, POWER SUPPLY""", "cat": """it_hardware"""},
{ "name": """BATTERY 9 VOLT TRANSISTOR SMALL""", "cat": """it_hardware"""},
{ "name": """BATTERY BACK-UP SYSTEM""", "cat": """it_hardware"""},
{ "name": """BATTERY FLASHLIGHT SIZE C""", "cat": """it_hardware"""},
{ "name": """BATTERY PENLIGHT SIZE AAA""", "cat": """it_hardware"""},
{ "name": """BATTERY PENLITE SIZE AA""", "cat": """it_hardware"""},
{ "name": """Poultry Equipment Maintenance and Repair""", "cat": """animal"""},
{ "name": """Braces: Monitor, PC's, CRT's, Desk Top Printers, etc., Envir""", "cat": """it_hardware"""},
{ "name": """CABLE, COMMUNICATIONS, AUDIO/VIDEO""", "cat": """it_hardware"""},
{ "name": """CABLE, COMPUTER CIRCUIT, (GENERAL USE). TO BE UL L""", "cat": """it_hardware"""},
{ "name": """CABLE, COMPUTER PATCH, PLENUM OR NON-PLENUM, 22-26""", "cat": """it_hardware"""},
{ "name": """CABLE, CONDUCTOR""", "cat": """it_hardware"""},
{ "name": """Cables: Printer, Disk, Network, etc.""", "cat": """it_hardware"""},
{ "name": """Camera Attachments: Adapter Rings, Collimators, Fi""", "cat": """it_hardware"""},
{ "name": """CAMERAS, CLOSED CIRCUIT TELEVISION""", "cat": """it_hardware"""},
{ "name": """CAMERAS, DIGITAL TYPE (INCL. DIGITAL NETWORK CAMERAS)""", "cat": """it_hardware"""},
{ "name": """CAMERAS, DIGITAL, LCD""", "cat": """it_hardware"""},
{ "name": """Cameras, Movie; and Accessories""", "cat": """it_hardware"""},
{ "name": """CAMERAS, VIDEO""", "cat": """it_hardware"""},
{ "name": """CAMERAS, VIDEO, FOR USE IN POLICE VEHICLES""", "cat": """it_hardware"""},
{ "name": """CARDS, ADAPTER, FOR COMPUTER GRAPHICS""", "cat": """it_hardware"""},
{ "name": """CARDS, ETHERNET ADAPTER, MICROCOMPUTER""", "cat": """it_hardware"""},
{ "name": """CARDS, MEMORY""", "cat": """it_hardware"""},
{ "name": """CHARGERS, BATTERY""", "cat": """it_hardware"""},
{ "name": """COMMUNICATIONS""", "cat": """it_hardware"""},
{ "name": """Communications: Networking, Linking, Fiber Modems, Power Ove""", "cat": """it_hardware"""},
{ "name": """Computer Accessories (Not Otherwise Classified) Rental""", "cat": """it_hardware"""},
{ "name": """Computer Hardware""", "cat": """it_hardware"""},
{ "name": """COMPUTER HARDWARE AND PERIPHERALS FOR MICROCOMPUTE""", "cat": """it_hardware"""},
{ "name": """Computer supplies""", "cat": """it_hardware"""},
{ "name": """Computers, Data Processing Equipment and Accessori""", "cat": """it_hardware"""},
{ "name": """Consoles, Police Vehicle (Includes Controls for P.""", "cat": """it_hardware"""},
{ "name": """Copy Machine (Including Cost-Per-Copy Type Leases)""", "cat": """it_hardware"""},
{ "name": """Copy Machine Maintenance and Repair""", "cat": """it_hardware"""},
{ "name": """DESK/WORKSTATION, DATA PROCESSING, WITH CRT VIEWIN""", "cat": """it_hardware"""},
{ "name": """DETECTION SYSTEM, VEHICLE""", "cat": """it_hardware"""},
{ "name": """DISK DRIVES, HARD DRIVE""", "cat": """it_hardware"""},
{ "name": """Driver and Hardware Support Programs""", "cat": """it_hardware"""},
{ "name": """Electronic and Communication Equipment Services (I""", "cat": """it_hardware"""},
{ "name": """Electronic Equipment Maintenance and Repair""", "cat": """it_hardware"""},
{ "name": """Emergency Back-up Services and Facilities for Data""", "cat": """it_hardware"""},
{ "name": """Expansion/Accelerator Boards: Hard Drive Controlle""", "cat": """it_hardware"""},
{ "name": """FAX SERVERS, NETWORK, TOKEN RING""", "cat": """it_hardware"""},
{ "name": """Fiber Optics Cables, Interconnecting Components, a""", "cat": """it_hardware"""},
{ "name": """FILTERS, CAMERA""", "cat": """it_hardware"""},
{ "name": """Gates, Electric (Card Reader, etc.) Maintenance an""", "cat": """it_hardware"""},
{ "name": """Gates, Electric (Including Card Readers, etc.)""", "cat": """it_hardware"""},
{ "name": """HEADSETS, TELEPHONE""", "cat": """it_hardware"""},
{ "name": """Information Highway Electronic Services (Internet,""", "cat": """it_hardware"""},
{ "name": """INSTALLATION OF COMPUTERS, PERIPHERALS, AND RELATE""", "cat": """it_hardware"""},
{ "name": """Installation of Computers, Peripherals, and Relate""", "cat": """it_hardware"""},
{ "name": """INSTALLATION, MAINTENANCE AND REPAIR SERVICES, DATA CENTER C""", "cat": """it_hardware"""},
{ "name": """INSTALLATION, RELATED COMPUTER EQUIPMENT, (NOT OTHERWISE CLA""", "cat": """it_hardware"""},
{ "name": """KEYBOARD ARM, ADJUSTABLE""", "cat": """it_hardware"""},
{ "name": """KEYBOARD SUPPORT MECHANISM AND PLATFORM, ARTICULAT""", "cat": """it_hardware"""},
{ "name": """KEYBOARD, MICROCOMPUTER""", "cat": """it_hardware"""},
{ "name": """Keyboards""", "cat": """it_hardware"""},
{ "name": """MAINTENANCE, MAINFRAME COMPUTER HARDWARE""", "cat": """it_hardware"""},
{ "name": """MICE, COMPUTER""", "cat": """it_hardware"""},
{ "name": """Microcomputers, Desktop or Towerbased""", "cat": """it_hardware"""},
{ "name": """Microcomputers, Desktop or Towerbased, Environmentally Certi""", "cat": """it_hardware"""},
{ "name": """Microcomputers, Handheld, Laptop, and Notebook""", "cat": """it_hardware"""},
{ "name": """Microcomputers, Handheld, Laptop, and Notebook, ECO Certifie""", "cat": """it_hardware"""},
{ "name": """MICROCOMPUTERS, LAPTOP""", "cat": """it_hardware"""},
{ "name": """Microcomputers, Multi-Processor""", "cat": """it_hardware"""},
{ "name": """MICROPHONES AND ACCESSORIES""", "cat": """it_hardware"""},
{ "name": """MICROPHONES AND PARTS (BRAND LISTED OR EQUAL)""", "cat": """it_hardware"""},
{ "name": """Microphones and Related Equipment: Chestsets, Earp""", "cat": """it_hardware"""},
{ "name": """MODULES, MEMORY, RAM""", "cat": """it_hardware"""},
{ "name": """Monitors, Color and Monochrome (CGA, VGA, SVGA, et""", "cat": """it_hardware"""},
{ "name": """MONITORS, COLOR, FOR COMPUTERS""", "cat": """it_hardware"""},
{ "name": """MONITORS, TELEVISION""", "cat": """it_hardware"""},
{ "name": """Mounting Hardware: Laptops, GPS, Cameras, Electronic Devices""", "cat": """it_hardware"""},
{ "name": """Network Components: Adapter Cards, Bridges, Connec""", "cat": """it_hardware"""},
{ "name": """PARTS & ACCESSORIES, EXTERNAL, CD ROM""", "cat": """it_hardware"""},
{ "name": """PLOTTERS, PARTS AND ACCESSORIES""", "cat": """it_hardware"""},
{ "name": """Printers, Inkjet""", "cat": """it_hardware"""},
{ "name": """PRINTERS, INKJET, W/ 6 FT. MIN. PRINTER CABLES, BR""", "cat": """it_hardware"""},
{ "name": """Printers, Laser""", "cat": """it_hardware"""},
{ "name": """Printers, Thermal""", "cat": """it_hardware"""},
{ "name": """PRINTERS, THERMAL, LABEL PRINTER""", "cat": """it_hardware"""},
{ "name": """Projection Devices and Accessories: Enviromentally Certified""", "cat": """it_hardware"""},
{ "name": """Projectors (Not Otherwise Classified): Combination""", "cat": """it_hardware"""},
{ "name": """RADIO COMMUNICATION, TELEPHONE, AND TELECOMMUNICAT""", "cat": """it_hardware"""},
{ "name": """RADIOS, MOBILE, HIGH FREQUENCY, INCLUDING EXTENDED""", "cat": """it_hardware"""},
{ "name": """RADIOS, TWO-WAY, PORTABLE PACKAGE""", "cat": """it_hardware"""},
{ "name": """RECEPTACLES, POWER, VEHICLE (TO CONNECT POWER SUPP""", "cat": """it_hardware"""},
{ "name": """RECORDER/PLAYER, STD CASSETTE""", "cat": """it_hardware"""},
{ "name": """RECORDER/PLAYER, VIDEO CASSETTE""", "cat": """it_hardware"""},
{ "name": """SERVERS, FILE, MICROCOMPUTER""", "cat": """it_hardware"""},
{ "name": """SPEAKERS""", "cat": """it_hardware"""},
{ "name": """Storage Devices, Electronic (Disk Drive Compatible""", "cat": """it_hardware"""},
{ "name": """Storage Services, Data Media""", "cat": """it_hardware"""},
{ "name": """SWITCHES, FOR COMPUTERS""", "cat": """it_hardware"""},
{ "name": """Tape Recorders, Decks, Players, etc., Sound (Not f""", "cat": """it_hardware"""},
{ "name": """Teleconference Systems, Audio/Video""", "cat": """it_hardware"""},
{ "name": """TELEVISION, COLOR, HIGH FOCUS PICTURE TUBE, W/RAND""", "cat": """it_hardware"""},
{ "name": """Two-Way Radio Receivers, Transmitters, Transceiver""", "cat": """it_hardware"""},
{ "name": """Two-Way Radio Supplies, Parts, and Accessories""", "cat": """it_hardware"""},
{ "name": """Two-Way Radio, Portable, Including Vehicle Radio R""", "cat": """it_hardware"""},
{ "name": """Video and Audio Systems, Accessories Parts (Closed Circuit""", "cat": """it_hardware"""},
{ "name": """VIDEO CAMERA AND ACCESSORIES, VHS HQ, CONSUMER GRA""", "cat": """it_hardware"""},
{ "name": """Video Camera-Recorders, Accessories and Parts (Tel""", "cat": """it_hardware"""},
{ "name": """VIDEO CAMERA, FULL RANGE DIGITAL AUTO FOCUS (MACRO""", "cat": """it_hardware"""},
{ "name": """VIDEO CAMERA, S-VHS CAMCORDER, PROFESSIONAL GRADE,""", "cat": """it_hardware"""},
{ "name": """VIDEO CAMERA, VHS CAMCORDER, PROFESSIONAL GRADE, A""", "cat": """it_hardware"""},
{ "name": """Video Cassette Recorders (VCR), Accessories and Pa""", "cat": """it_hardware"""},
{ "name": """Video Instrument Testing and Calibration Services""", "cat": """it_hardware"""},
{ "name": """Video Projectors, Accessories and Parts""", "cat": """it_hardware"""},
{ "name": """Video Recording""", "cat": """it_hardware"""},
{ "name": """VIDEO RECORDING SYSTEM AND AUDIO EQUIPMENT, VEHICL""", "cat": """it_hardware"""},
{ "name": """WARRANTY, EXTENDED, COMPUTER EQUIPMENT""", "cat": """it_hardware"""},
{ "name": """Wire and Cable, Electronic: Audio, Coaxial, Hook-U""", "cat": """it_hardware"""},
{ "name": """Application Service Provider (ASP), Web Based Hosted""", "cat": """it_software"""},
{ "name": """Application Software, Microcomputer""", "cat": """it_software"""},
{ "name": """Applications Software for Microcomputer Systems: B""", "cat": """it_software"""},
{ "name": """Business Software, Misc.: Agenda, Labels, Mail Lists""", "cat": """it_software"""},
{ "name": """Computer Aided Design and Vectorization Software""", "cat": """it_software"""},
{ "name": """Computer Aided Design Services""", "cat": """it_software"""},
{ "name": """Computer Software Consulting""", "cat": """it_software"""},
{ "name": """COMPUTER SOFTWARE FOR MICROCOMPUTERS (PREPROGRAMME""", "cat": """it_software"""},
{ "name": """Computer Systems, Digital""", "cat": """it_software"""},
{ "name": """DATA PROCESSING SERVICES AND SOFTWARE""", "cat": """it_software"""},
{ "name": """Database Software, Microcomputer""", "cat": """it_software"""},
{ "name": """GLOBAL POSITIONING SYSTEM (GPS) SUBSCRIPTION SERVICE""", "cat": """it_software"""},
{ "name": """LICENSE, APPLICATION SOFTWARE, MICROCOMPUTER""", "cat": """it_software"""},
{ "name": """MAINTENANCE AND LICENSE AGREEMENT SERVICES, MICROC""", "cat": """it_software"""},
{ "name": """Maintenance-computer software""", "cat": """it_software"""},
{ "name": """Positioning Systems, Satellite (Global Info. Syste""", "cat": """it_software"""},
{ "name": """Software""", "cat": """it_software"""},
{ "name": """Software Maintenance/Support""", "cat": """it_software"""},
{ "name": """SOFTWARE, CASHIERING AND REVENUE MANAGEMENT, MICROCOMPUTER""", "cat": """it_software"""},
{ "name": """SOFTWARE, MICROCOMPUTER, BUSINESS, MISCELLANEOUS,""", "cat": """it_software"""},
{ "name": """SOFTWARE, MICROCOMPUTER, UTILITIES, DIAGNOSTIC, IBM""", "cat": """it_software"""},
{ "name": """SOFTWARE, TRAINING AND TESTING COURSES, FOR PROFES""", "cat": """it_software"""},
{ "name": """Training, Computer Based (Software Supported)""", "cat": """it_software"""},
{ "name": """WEB ACCESS - INTERNET SERVICE PROVIDER""", "cat": """it_software"""},
{ "name": """Legal Consulting""", "cat": """legal"""},
{ "name": """Legal Services Including Depositions and Expert Wi""", "cat": """legal"""},
{ "name": """Legal Services, Attorneys""", "cat": """legal"""},
{ "name": """Services-court costs""", "cat": """legal"""},
{ "name": """Services-legal fees""", "cat": """legal"""},
{ "name": """Transcription Services: Legal and Medical""", "cat": """legal"""},
{ "name": """Chemicals for Personal Defense (Mace, etc.)""", "cat": """riot"""},
{ "name": """STRAPS, HANDCUFF""", "cat": """restraints"""},
{ "name": """ZIPPERS, NYLON OR POLYESTER FABRIC, PLASTIC TEETH,""", "cat": """restraints"""},
{ "name": """GRENADES, RIOT CONTROL""", "cat": """riot"""},
{ "name": """HELMET ACCESSORIES, POLICE TYPE""", "cat": """armor"""},
{ "name": """HELMETS, SAFETY, POLICE TYPE""", "cat": """armor"""},
{ "name": """MASKS, GAS""", "cat": """riot"""},
{ "name": """PARTS AND ACCESSORIES, GAS MASK""", "cat": """riot"""},
{ "name": """Riot Control Equipment (Not Otherwise Classified)""", "cat": """riot"""},
{ "name": """Tear Gas, Tear Gas Guns, and Ammunition""", "cat": """tear_gas"""},
{ "name": """Guns, Stun (Nonlethal)""", "cat": """stun"""},
{ "name": """CAMERA, VIDEO SURVEILLANCE (INDOOR-CLOSE QUARTER)""", "cat": """surveillance"""},
{ "name": """Communications Systems; TV; Microwave; Telephone; Computer""", "cat": """surveillance"""},
{ "name": """DATA COLLECTOR AND SCANNER, PORTABLE""", "cat": """surveillance"""},
{ "name": """Imaging Systems, Infrared Thermal (Not X-Ray)""", "cat": """surveillance"""},
{ "name": """INSTALLATION OF IN-CAR VIDEO SYSTEMS""", "cat": """surveillance"""},
{ "name": """LASER SPEED MEASURING AND RANGING DEVICES""", "cat": """surveillance"""},
{ "name": """Metal Finders and Detectors, Pipe Locators, etc.""", "cat": """surveillance"""},
{ "name": """MONITORING EQUIPMENT, SECURITY, CLOSED CIRCUIT, FO""", "cat": """surveillance"""},
{ "name": """Night Vision Systems""", "cat": """surveillance"""},
{ "name": """NIGHT VISION SYSTEMS""", "cat": """surveillance"""},
{ "name": """Police Investigation Robots""", "cat": """surveillance"""},
{ "name": """Radar Instruments (Marine Type), and Accessories:""", "cat": """surveillance"""},
{ "name": """Radar Instruments, Traffic Enforcement Type (Inclu""", "cat": """surveillance"""},
{ "name": """RADAR SPEED MEASURING DEVICE OPERATING WITH THE AU""", "cat": """surveillance"""},
{ "name": """RECOGNITION SYSTEM, LICENSE PLATES""", "cat": """surveillance"""},
{ "name": """Sonar Instruments, Research Type""", "cat": """surveillance"""},
{ "name": """Sound Analysis Equipment and Accessories: Noise Me""", "cat": """surveillance"""},
{ "name": """SURVEILLANCE AND COUNTER SURVEILLANCE EQUIPMENT AND SUPPLIES""", "cat": """surveillance"""},
{ "name": """Surveillance and Countersurveillance Equipment and""", "cat": """surveillance"""},
{ "name": """Surveillance Services""", "cat": """surveillance"""},
{ "name": """Video and Audio Surveillance Systems (Closed Circu""", "cat": """surveillance"""},
{ "name": """Actuators and Controls (For Robotics, Servo System""", "cat": """tactical"""},
{ "name": """Animal Cages and Supplies (Including Litter)""", "cat": """animal"""},
{ "name": """ANIMAL CARE""", "cat": """animal"""},
{ "name": """Animal Training Equipment and Supplies""", "cat": """tbd"""},
{ "name": """BATONS, PATROLMAN""", "cat": """tactical"""},
{ "name": """Binoculars""", "cat": """tactical"""},
{ "name": """Bomb Detection Equipment and Supplies""", "cat": """tactical"""},
{ "name": """Bomb Protection Devices and Supplies""", "cat": """tactical"""},
{ "name": """Breathing Equipment for Firemen""", "cat": """tbd"""},
{ "name": """CABLE TIES, SELF-LOCKING, NYLON AND PLASTIC""", "cat": """restraints"""},
{ "name": """Counseling""", "cat": """tbd"""},
{ "name": """Court Reporting Services""", "cat": """tbd"""},
{ "name": """Dogs, All Types""", "cat": """animal"""},
{ "name": """Drugs""", "cat": """tbd"""},
{ "name": """Equestrian Equipment, Clothing and Supplies (Inclu""", "cat": """animal"""},
{ "name": """FAX MACHINE/COPIER/SCANNER/COLOR PRINTER COMBINATI""", "cat": """tbd"""},
{ "name": """Food/storage for animals""", "cat": """animal"""},
{ "name": """Forced Entry Equipment and Supplies (Battering Ram""", "cat": """tactical"""},
{ "name": """FORMS, CONTINUOUS, CUSTOM""", "cat": """tbd"""},
{ "name": """FORMS, PRINTED""", "cat": """tbd"""},
{ "name": """Handcuffs and Leg Irons""", "cat": """restraints"""},
{ "name": """HAY""", "cat": """animal"""},
{ "name": """HELMETS, BLASTING, PARTS & ACCESSORIES""", "cat": """tactical"""},
{ "name": """HELMETS, SAFETY, PILOT TYPE, INCLUDING PARTS AND ACCESSORIES""", "cat": """tactical"""},
{ "name": """HOLSTER""", "cat": """tactical"""},
{ "name": """Horses""", "cat": """animal"""},
{ "name": """IMAGING SYSTEMS, INFRARED THERMAL, INCLUDING PARTS AND ACCES""", "cat": """surveillance"""},
{ "name": """LIGHT TOWER, TRAILER MOUNTED,""", "cat": """tbd"""},
{ "name": """Mixed Feed, All Types (Includes Feed for Poultry,""", "cat": """animal"""},
{ "name": """Pizzas""", "cat": """tbd"""},
{ "name": """Printers, Laser, Environmentally Certified""", "cat": """tbd"""},
{ "name": """PRINTING OF FILE FOLDERS, SPECIAL TAB CUT, PRINTED""", "cat": """tbd"""},
{ "name": """PRINTING OF FORMS, CONTINUOUS, CARD STOCK, LAST CO""", "cat": """tbd"""},
{ "name": """Protection Services (Not Including Buildings)""", "cat": """tbd"""},
{ "name": """Psychologists/Psychological Services""", "cat": """tbd"""},
{ "name": """Reimbursed overtime""", "cat": """tbd"""},
{ "name": """Safes and Vaults Including Parts and Accessories""", "cat": """tbd"""},
{ "name": """SCANNERS/READERS, OPTICAL MARK READERS""", "cat": """tbd"""},
{ "name": """Scuba and Skin Diving Equipment""", "cat": """tactical"""},
{ "name": """SERVICES NOT OTHERWISE CLASSIFIED""", "cat": """tbd"""},
{ "name": """TASSELS, BATON""", "cat": """tactical"""},
{ "name": """TOURNIQUET""", "cat": """tbd"""},
{ "name": """TRANSPORTATION SERVICES FOR PAROLE VIOLATORS""", "cat": """tbd"""},
{ "name": """VITAMINS, VETERINARY""", "cat": """animal"""},
{ "name": """WHISTLES, POLICE""", "cat": """tactical"""},
{ "name": """CARTRIDGES, TEAR GAS""", "cat": """tear_gas"""},
{ "name": """GRENADES, TEAR GAS""", "cat": """tear_gas"""},
{ "name": """Artists""", "cat": """the_fuck"""},
{ "name": """Expert System Software""", "cat": """the_fuck"""},
{ "name": """Makeup""", "cat": """the_fuck"""},
{ "name": """POLICE EQUIPMENT AND SUPPLIES""", "cat": """the_fuck"""},
{ "name": """Skis, Jet""", "cat": """the_fuck"""},
{ "name": """SNACKS, PUFFED, CHEESE FLAVOR.""", "cat": """the_fuck"""},
{ "name": """Educational travel""", "cat": """travel"""},
{ "name": """Hotel/Motel Accomodations""", "cat": """travel"""},
{ "name": """Staff dev-travel""", "cat": """travel"""},
{ "name": """Travel city business""", "cat": """travel"""},
{ "name": """Travel City Business""", "cat": """travel"""},
{ "name": """Travel, Non-Local (Scheduled and Unscheduled), Pro""", "cat": """travel"""},
{ "name": """Armored Car Services""", "cat": """vehicles"""},
{ "name": """Automobile and Other Passenger Vehicles Maintenance, Repair""", "cat": """vehicles"""},
{ "name": """Automobiles and Other Passenger Vehicles (Includin""", "cat": """vehicles"""},
{ "name": """Automobiles and Other Passenger Vehicles, Rental or Lease""", "cat": """vehicles"""},
{ "name": """AUTOMOBILES, FULL SIZE, 4-DOOR SEDAN""", "cat": """vehicles"""},
{ "name": """AUTOMOTIVE MAINTENANCE ITEMS AND REPAIR/REPLACEMEN""", "cat": """vehicles"""},
{ "name": """AUTOMOTIVE VEHICLES AND TRANSPORT EQUIP (INCLUDING TRAILERS)""", "cat": """vehicles"""},
{ "name": """Boat Fenders""", "cat": """vehicles"""},
{ "name": """Boats and Motors Maintenance and Repair""", "cat": """vehicles"""},
{ "name": """Boats, 21 Feet and Under""", "cat": """vehicles"""},
{ "name": """BOATS, MOTORS, AND MARINE EQUIPMENT""", "cat": """vehicles"""},
{ "name": """Boats, Over 21 Feet (Including Ferries)""", "cat": """vehicles"""},
{ "name": """Body and Frame Parts (Not Otherwise Classified)""", "cat": """vehicles"""},
{ "name": """BRAKES""", "cat": """vehicles"""},
{ "name": """Brakes, Repairs, and Replacements (Not Electric Co""", "cat": """vehicles"""},
{ "name": """DECALS, VEHICLE""", "cat": """vehicles"""},
{ "name": """Fleet-equip.preventative maint""", "cat": """vehicles"""},
{ "name": """Fuel System Maintenance and Repair""", "cat": """vehicles"""},
{ "name": """Gasoline/oil/grease""", "cat": """vehicles"""},
{ "name": """General Maintenance, Vehicle (Not Otherwise Classi""", "cat": """vehicles"""},
{ "name": """Grille Guards""", "cat": """vehicles"""},
{ "name": """Headlights, Accessories and Parts (Including Lamps""", "cat": """vehicles"""},
{ "name": """LIGHTS, NAVIGATION, MARINE""", "cat": """vehicles"""},
{ "name": """LIGHTS, WARNING, STROBE TYPE, PERMANENT MOUNT""", "cat": """vehicles"""},
{ "name": """Lights: Anti-Collision, Landing, Navigations, etc.""", "cat": """vehicles"""},
{ "name": """Maintenance-vehicles""", "cat": """vehicles"""},
{ "name": """MIRRORS, MISC. AUTOMOTIVE  (BRAND LISTED OR EQUAL)""", "cat": """vehicles"""},
{ "name": """Mirrors, Safety and Security (For Blind Corners in""", "cat": """vehicles"""},
{ "name": """Motor and Engine Maintenance and Repair, Small Gas""", "cat": """vehicles"""},
{ "name": """Motorcycles, Accessories, and Parts""", "cat": """vehicles"""},
{ "name": """Motorcycles, Bicycles, Motor Scooters, and Truckst""", "cat": """vehicles"""},
{ "name": """Motors and Engines (Including Parts), Industrial,""", "cat": """vehicles"""},
{ "name": """Off-Road Vehicles (Tracked or Wheeled)""", "cat": """vehicles"""},
{ "name": """Rental-vehicles/buses""", "cat": """vehicles"""},
{ "name": """Replacement Vehicles""", "cat": """vehicles"""},
{ "name": """RETREADING MEDIUM TRUCK/BUS TIRES, RADIAL, CONVENT""", "cat": """vehicles"""},
{ "name": """Short Wheelbase, Two-and Four-Wheel Drive Vehicle""", "cat": """vehicles"""},
{ "name": """SUPPLIES, MARINE (MISC.)""", "cat": """vehicles"""},
{ "name": """SUV, Police Patrol""", "cat": """vehicles"""},
{ "name": """TIRES AND TUBES""", "cat": """vehicles"""},
{ "name": """TRAILER, GENERAL PURPOSE, SINGLE AXLE, DUAL WHEEL""", "cat": """vehicles"""},
{ "name": """TRAILER, RECREATIONAL AND FIRE""", "cat": """vehicles"""},
{ "name": """TRAILER, SEMI, MATERIAL TRANSPORT, 30 CU YD, HYDRA""", "cat": """vehicles"""},
{ "name": """Trailers, Custom: Personnel, Food Service, Equipme""", "cat": """vehicles"""},
{ "name": """Trailers, Flat Bed""", "cat": """vehicles"""},
{ "name": """Trailers, Gooseneck""", "cat": """vehicles"""},
{ "name": """Transportation-city veh fuel""", "cat": """vehicles"""},
{ "name": """TRUCK, RESCUE/COMMAND, 40K GVW""", "cat": """vehicles"""},
{ "name": """Trucks (One Ton and Less Capacity)""", "cat": """vehicles"""},
{ "name": """Trucks (Over One Ton Capacity)""", "cat": """vehicles"""},
{ "name": """TRUCKS, PICKUP, 1/2 TON""", "cat": """vehicles"""},
{ "name": """TRUCKS, PICKUP, FLEETSIDE, CREW CAB, TWO AND FOUR""", "cat": """vehicles"""},
{ "name": """TRUCKS, PICKUP, REGULAR CAB, ONE TON""", "cat": """vehicles"""},
{ "name": """UTILITY VEHICLE, PASSENGER, 2-""", "cat": """vehicles"""},
{ "name": """UTILITY VEHICLE, PASSENGER, 4-""", "cat": """vehicles"""},
{ "name": """VAN, FULL SIZE 10-15 PASSENGER""", "cat": """vehicles"""},
{ "name": """VANS, CARGO, STANDARD""", "cat": """vehicles"""},
{ "name": """Vans, Modified (Custom)""", "cat": """vehicles"""},
{ "name": """VANS, PASSENGER""", "cat": """vehicles"""},
{ "name": """VEHICLE INSPECTION SERVICES""", "cat": """vehicles"""},
{ "name": """VEHICLES, SPORT UTILITY, TWO-WHEEL DRIVE""", "cat": """vehicles"""},
{ "name": """VEHICLES, UTILITY, TWO AND FOUR WHEEL DRIVE""", "cat": """vehicles"""},
{ "name": """SEDAN, POLICE PATROL""", "cat": """vehicles"""}]